id = "mint"
name = "Mint"
version = "1.0.0"
schema_version = 1
authors = ["Gusztáv Szikszai <gus@mint-lang.com>"]
description = "Language Support for the Mint programming language"
repository = "https://github.com/mint-lang/zed-mint-extension"

[grammars.mint]
repository = "https://github.com/mint-lang/mint"
commit = "8989b87f48a6231f9eebb73b238bea391d68052b"
path = "grammar"
