id = "mint"
name = "Mint"
version = "1.0.0"
schema_version = 1
authors = ["Gusztáv Szikszai <gus@mint-lang.com>"]
description = "Language Support for the Mint programming language"
repository = "https://github.com/mint-lang/zed-mint-extension"

[grammars.mint]
repository = "https://github.com/mint-lang/mint"
commit = "2269a1b421ec37bb4919eb5ab4820e4780f9ddc1"
path = "grammar"
