id = "mint"
name = "Mint"
version = "1.0.0"
schema_version = 1
authors = ["Gusztáv Szikszai <gus@mint-lang.com>"]
description = "Language Support for the Mint programming language"
repository = "https://github.com/mint-lang/zed-mint-extension"

[grammars.mint]
repository = "https://github.com/mint-lang/mint"
commit = "fbf1f43b7cf6c65d9136e639349aaf91eae9f618"
path = "grammar"
